### ISSUE TITLE
Works with Airthings Hub

### ISSUE THREAD

**Issue by fancypants66** [michaelahern/homebridge-airthings#1]
To confirm, works with an Airthings Hub and two Wave Plus sensors. I mistakenly configured the Hub as an accessory alongside the two Wave Plus sensors - but quickly realized the Wave Plus sensors are the only accessories that need to be configured in Homebridge in my case. Samples are being successfully refreshed every 150 seconds (battery, co2, humidity, pressure, radonShortTermAvg, rssi, temp, time, voc, relayDeviceType). Haven't found a HomeKit app that displays pressure and radon levels, but not sure that's something that's supported or not. Keep up the great work!

**Comment by michaelahern** [comment]
Thank you for the feedback and testing! Have updated the readme to note this configuration has been tested..
