### ISSUE TITLE
Make battery status appear in Apples Home app

### ISSUE THREAD

**Issue by malmentm** [michaelahern/homebridge-airthings#10]
Hello!
I wonder if this is possible or is there some limitation that prevents this? I can see in other threads that its available in 3rd party HomeKit applications though. But it would be nice to have it in the Apple Home app aswell.

**Comment by michaelahern** [comment]
See #4 for additional details on this, but short summary is this is a limitation in the Apple Home app..

**Comment by malmentm** [comment]
saw you added battery in latest version. Thanks :D
