### ISSUE TITLE
Wrong sensor values

### ISSUE THREAD

**Issue by Windewigg** [michaelahern/homebridge-airthings#18]
Hi there! Great plugin, thanks a lot. I am running a View Plus. The detailed sensor values are being read out correctly, as shown in the log:
{"battery":100,"co2":739,"humidity":57,"pm1":6,"pm25":6,"pressure":958.4,"radonShortTermAvg":15,"temp":22.8,"time":...,"voc":181,"relayDeviceType":"hub"}
I have understood, that HomeKit limits the type of values that can be displayed, so radon cannot be displayed, right? 
But the values themselves are also displayed wrong, e. g. "VOC Density" is shown to be "550" (incorrect) though the read out value is "181" (correct) (see log above).
Do I have to do any corrections in the configuration or do you have an idea what's wrong. 
Thanks in advance!

**Comment by ninjas28** [comment]
They're different units, the Airthings measures VOC density in parts per billion and Homekit wants values in micrograms per cubic metre.

**Comment by michaelahern** [comment]
Yep, exactly. The default HomeKit characteristic expects micrograms per cubic meter. I've added a custom secondary characteristic to show VOC in pub in the latest version (v0.7). It won't display in the Apple Home app, but will be visible in some third-party HomeKit apps.

Also check out the latest version and readme for details on new Radon support in the latest version..
