### ISSUE TITLE
3 different Devices work with Airthings Hub

### ISSUE THREAD

**Issue by Flieger37** [michaelahern/homebridge-airthings#2]
Long awaited, now it's here .. thanx to Michael for the plugin.

I can confirm that the following devices are recognized by the plugin and are shown in HomeKit (each defined as a single accessory and in my case configured as sub-bridges):

- Airthings Wave Mini (3 Sensors: Air Quality+VOC, Humidity, Temperature)
- Airthings Wave (3 Sensors: Air Quality, Humidity, Temperature)
- Airthings Wave Plus (4 Sensors: Air Quality+VOC, CO2, Humidity, Temperature)

All three devices are connected to an Airthings Hub.

Radon is not known by Apple HomeKit, so there is no value for radon.

**Comment by michaelahern** [comment]
Thank you for the feedback and testing! Have updated the readme to note this configuration has been tested..
