### ISSUE TITLE
Request API Client Removed from Dashboard

### ISSUE THREAD

**Issue by jamestford** [michaelahern/homebridge-airthings#24]
Looks like Airthings has removed the ability to generate API keys from the dashboard. They have updated their documentation on generating oath here: https://developer.airthings.com/docs/api-authorization. Are there any free and open web api's that you can use to generate these?

**Comment by michaelahern** [comment]
It looks like they now support OAuth Code Flow grants in the Business API, but the [Consumer API docs](https://developer.airthings.com/docs/api-getting-started-consumer) still show Client Credential grants (Client ID and Secret key) as the primary supported mechanism. I also still see the Integration API bits in the Dashboard. What do you see at https://dashboard.airthings.com/integrations/api-integration when logged in?

**Comment by jamestford** [comment]
Interesting, seems to be a browser bug, after clearing the cache and reloading I was able to see the integration. Apologies. It is working fine, was able to configure a wave and view plus.
