### ISSUE TITLE
Direct connect to Airthings Wave Plus

### ISSUE THREAD

**Issue by akellbl4** [michaelahern/homebridge-airthings#25]
Arithings Wave Plus (and other sensors) has ability to connect via bluetooth and pull all of the metrics from it without going into the cloud.
For example Airthings has [repo](https://github.com/Airthings/waveplus-reader) that shows this ability.

I think this ability can be added to the package by reimplementaton of the package above into JS/TS.
Could you consider adding such functionality to the package? (I'm willing to help with it)

**Comment by michaelahern** [comment]
There are a few existing Homebridge plugins that target Airthings Wave devices over Bluetooth. Have you tried any of these?

https://www.npmjs.com/search?q=keywords%3Ahomebridge-plugin%20airthings

**Comment by akellbl4** [comment]
@michaelahern I didn't do broader search and that's my fault. Thank you for pointing to the package. So I think this issue is pointless.
