### ISSUE TITLE
Radon in EVE App

### ISSUE THREAD

**Issue by Flieger37** [michaelahern/homebridge-airthings#3]
I read in other Airthings plugin descriptions, that they managed  to show the radon values in EVE App.
Is there a chance to implement the radon values for the EVE App in this plugin?

**Comment by michaelahern** [comment]
Do you have any examples of plugins (Airthings or otherwise) that are displaying radon values in Eve? I haven't been able to find a good way to feed Radon data into HomeKit. Would note this plugin takes Radon readings into account as part of the overall Air Quality sensor output.

**Comment by Flieger37** [comment]
The plug-in, where I read about EVE support is this one: HSkul/homebridge-airthings-wave

https://github.com/HSkul/homebridge-airthings-wave

but because of the Bluetooth/Pi solution that does not work with my 3 sensors, I never checked, if it is running .

**Comment by michaelahern** [comment]
Thanks for the example there, super helpful. I've added a custom Radon level charactertistic to the Air Quality service in v0.2.0 and was able to see the value in Eve Home and Home+. Can you test this out and see if it works for you?

**Comment by Flieger37** [comment]
Thanks for this quick update of your plugin. Below you find three screenshots of Wave Plus, Wave Mini and Wave Radon in EVE App - looks good and also works in CONTROLLER App.

I don't own the HOME+ App, but I think it will be displayed there also.

![IMG_6483](https://user-images.githubusercontent.com/65550366/140658882-85a3b9f8-af59-4c75-8772-78d8b11daa18.PNG)

![IMG_6482](https://user-images.githubusercontent.com/65550366/140658890-52485020-dd82-4cc9-8469-525db24e3e44.PNG)

![IMG_6484](https://user-images.githubusercontent.com/65550366/140658895-e0237f5a-2596-494c-9035-935e350e8ece.PNG)

**Comment by michaelahern** [comment]
Thanks for testing and the screenshots for reference!
