### ISSUE TITLE
Dead battery on Airthings wave leads to "leak alert" on apple home app

### ISSUE THREAD

**Issue by the-datasmith** [michaelahern/homebridge-airthings#32]
I too really appreciate the integration now possible with home bridge and your Airthings plug in!

I recently ignored low battery alerts on my Airthings Wave Plus.  When the battery finally died, I got an "leak" alert from my apple home app.
That all cleared up when I replaced the battery but it led me to wonder.... The word "leak" implies a water leak to me, but perhaps you mean a radon leak?    Still it's an odd word.
In any event, I found it odd that I would get a warning about a problem when I simply had a dead battery.

**Comment by michaelahern** [comment]
Made a number of improvements in v1.0.0 to improve validation around sensor data updates and prevent some HomeKit exceptions. Cannot guarantee those changes will solve this specific issue, but please re-open if it reoccurs and provide debug log output if possible.
