### ISSUE TITLE
Water leak being incorrectly detected

### ISSUE THREAD

**Issue by Morac2** [michaelahern/homebridge-airthings#35]
I have an Airthings View Plus.  I added it to Homebridge and a water detector was incorrectly added to HomeKit and it is always showing as "leak detected".  I can't find any way to remove the water detector accessory which shouldn't be there.

I set the radon detection to 4.  The AirThings View Plus is currently showing 0.1, so it shouldn't be showing a "leak".

Edit:

Never mind it looks likes this plugin uses different units than AirThings does.

**Comment by systox** [comment]
Just had this same problem. Can we have parity with radon detection units? If no; thanks anyway glad it's documented here. Great plugin.
