### ISSUE TITLE
Air Quality uses CO2 but doesn’t show it

### ISSUE THREAD

**Issue by Morac2** [michaelahern/homebridge-airthings#36]
The Air Quality uses PM2, VOC and CO2, but only shows the PM2 and VOC, so many times it will show as fair or poor, but I have to dig into the CO2 sensor to see why. 

<img width="352" alt="image" src="https://github.com/michaelahern/homebridge-airthings/assets/1596194/b4861317-a741-4de0-a3c0-2abe48cb684f">

**Comment by Morac2** [comment]
On a side note, I don’t know where that VOC value came from. The actual VOC value at the time was 167 ppb.  There is no option to show VOC in ug/m3 in the AirThings app.

<img width="660" alt="image" src="https://github.com/michaelahern/homebridge-airthings/assets/1596194/b4458636-fa0e-4b19-a3bf-54dc6d3238a0">

**Comment by michaelahern** [comment]
Version 1.1 includes updates to show CO2 and Humidity values under the Air Quality sensor. Radon is not an officially support characteristic in HomeKit and will not be visible in the Apple Home app. Latest version also includes the ability to configure which sensors are used in calculating the Air Quality value as well. Thank you for raising!
