### ISSUE TITLE
VOC is not accurate 

### ISSUE THREAD

**Issue by Morac2** [michaelahern/homebridge-airthings#37]
The VOC µg/m³ value as reported by the AirThings dashboard does not match the µg/m³ value as reported in Home.

Looking at the code it looks like the calculation is completely wrong.

According to https://www.breeze-technologies.de/blog/air-pollution-how-to-convert-between-mgm3-µgm3-ppm-ppb/ 

`Concentration (µg/m3) = molecular weight x concentration (ppb) ÷ 24.45`

The code is doing some weird calculation involving temperate and pressure. 

https://github.com/michaelahern/homebridge-airthings/blob/5198e29f42b56ec2ae1c19d2e9237b4e339d5525/src/plugin.ts#L257

<img width="405" alt="image" src="https://github.com/michaelahern/homebridge-airthings/assets/1596194/baf5319d-d19b-47db-a736-4925b4efd86b">

<img width="349" alt="image" src="https://github.com/michaelahern/homebridge-airthings/assets/1596194/7803c1cb-faaf-4a0d-928f-50d268ebdbbc">

<img width="347" alt="image" src="https://github.com/michaelahern/homebridge-airthings/assets/1596194/0ab99fa7-d19f-4a6c-a1df-8224753badc6">

The molecular weight can be calculated by comparing values in the dashboard when set to ppb and µg/m3.  By my calculation it is 55.653

<img width="384" alt="image" src="https://github.com/michaelahern/homebridge-airthings/assets/1596194/8832942d-ac5a-4850-8a0d-375afb11c9aa">

<img width="362" alt="image" src="https://github.com/michaelahern/homebridge-airthings/assets/1596194/44de4cfa-40fe-47a4-9c89-885a057cb0af">

**Comment by michaelahern** [comment]
Version 1.1 includes updated VOC conversion logic that mirrors the Airthings logic. Thank you for raising!
