### ISSUE TITLE
Battery status

### ISSUE THREAD

**Issue by Flieger37** [michaelahern/homebridge-airthings#4]
As Apple HomeKit supports to show the battery status for HomeKit devices: is it possible to implement the battery status for the Airthings devices (does the Airthings API provide the value)?

**Comment by michaelahern** [comment]
The Airthings API provides the battery level. The plugin is currently reporting low battery status into HomeKit, which only shows an alert when it falls below 10%. The iOS home app wasn't showing battery level, so didn't include it in the first iteration of the plugin, but the Eve Home app looks like it shows it if available. Let me add this to the next release!

**Comment by Flieger37** [comment]
I saw a battery level in the status screen for example for EVE Aqua and was wondering if this might work with Airthings:

![3444D84D-ADDD-4BBF-8AF3-EB5EE071FCFA](https://user-images.githubusercontent.com/65550366/140637917-f5969a62-35b1-4460-9a9e-aac76ac8c35a.png)

**Comment by michaelahern** [comment]
I've added this to the Air Quality service for each device in v0.2.0 and was able to show this in Eve Home and Home+. Can you test this out and see if it works for you?

**Comment by Flieger37** [comment]
See "issue #3" for screenshots. Works fine for Wave Plus, Wave Mini and Wave Plus. Thanks, Michael!

**Comment by michaelahern** [comment]
Thanks for testing!

**Comment by malmentm** [comment]
@michaelahern why does the battery only shows in Eve app and Home+? Why can't it show in the apple home app? :) Is there some kind of limitation?

**Comment by michaelahern** [comment]
I believe it's a limitation of the Apple Home app UI. The underlying HomeKit data will have this populated, but it's up to each app to determine how/what to display.
