### ISSUE TITLE
Multiple Airthings Devices

### ISSUE THREAD

**Issue by realtoinedeal8** [michaelahern/homebridge-airthings#43]
love the plugin. But i am a total noob to this world of homebridge and plugins. I have about 6 airthings minis in my house. How do I make thee plug in read all of them? or do I just pick one and stick with that one? sorry if it is a dumb question.

**Comment by michaelahern** [comment]
Not a dumb question! When you go to the Airthings plugin config, click the "+" button next to "Save" to add another device. Assuming the devices are all on the same Airthings account, you can use the same Client ID and Secret and just set a unique name and serial number for each device.

![new](https://github.com/user-attachments/assets/fb24a995-5700-4317-9142-9ca8e71f9c12)

**Comment by michaelahern** [comment]
Also, would note that with 6 devices, you'll hit the Airthings API rate limits with the default plugin config. Would recommend setting Advanced Settings --> Airthings API Refresh Interval to 200 seconds for each device to prevent hitting rate limit errors.
