### ISSUE TITLE
Add support for Wave Enhance

### ISSUE THREAD

**Issue by Morac2** [michaelahern/homebridge-airthings#45]
I have a Wave Plus and View Pro and both show up in HomeKit, but a new Wave Enhance I bought is not be detected by this plugin. I added the same client and secret that I used for the other 2 and its serial number. 

It’s not on the supported list so I’m guessing it needs to be added.  Its serial number starts with 3220. 

It supports the same sensors as the Wave Plus minus the radon sensor.  It adds a light and noise sensor. 

https://www.airthings.com/wave-enhance

**Comment by michaelahern** [comment]
Released as v1.4.0 -- can you help test with your device?

**Comment by Morac2** [comment]
> Released as v1.4.0 -- can you help test with your device?

Well I wrote the PR so I was running my version already, but I upgraded to version v1.4.0 and it's still working.
