### ISSUE TITLE
Request failed with status code 429

### ISSUE THREAD

**Issue by 9zero8** [michaelahern/homebridge-airthings#48]
I have several Airthings devices configured and after a day or so of having it setup I started seeing repeated errors stating "Request failed with status code 429".  I believe this has to do with too many requests being made but I can't see a way to decrease the rate.

**Comment by michaelahern** [comment]
Please see the note in the readme about configuring a optional refresh interval config field in the plugin's Homebridge config to reduce the frequency of requests to the Airthings API..

https://consumer-api-doc.airthings.com/docs/api/rate-limit
