### ISSUE TITLE
Use of occupancy sensors

### ISSUE THREAD

**Issue by Flieger37** [michaelahern/homebridge-airthings#6]
The weather plugin "naofireblade/homebridge-weather-plus" uses occupancy sensors to display values for example of cloud cover, Wind speed, Wind direction and others which are normally not supported by Apple HomeKit.

Might this be a way to show radon values or mold index (Wave Mini)?

I am not sure about air pressure, if this is a native HomeKit value or also just displayable as an occupancy sensor (?)

![IMG_6479](https://user-images.githubusercontent.com/65550366/140641106-2624ab21-6389-4dcd-91c8-76b1ee9e2af4.PNG)

**Comment by michaelahern** [comment]
Keeping open to track Wave Mini Mold sensor in next round of updates..

**Comment by michaelahern** [comment]
Added support for mold sensor in v0.5.0.
