### ISSUE TITLE
Display CO2 levels

### ISSUE THREAD

**Issue by gleatherman** [michaelahern/homebridge-airthings#7]
Is it possible to display the current C02 level in the homekit icon similar to how Temp and Humidity levels are shown?

**Comment by michaelahern** [comment]
I believe that's a limitation in the Apple Home app. They seem to treat the CO2 as an alarm sensor, so it either shows nothing if CO2 is within normal levels or in alarm if CO2 is above normal levels. Digging into the sensor details shows the current levels though.
