### ISSUE TITLE
'VOC Density': characteristic was supplied illegal value

### ISSUE THREAD

**Issue by benjholl** [michaelahern/homebridge-airthings#8]
on higher VOC levels i get a warning like the following:

```
[05/01/2022, 19:58:04] [homebridge-airthings] This plugin generated a warning from the characteristic 'VOC Density': characteristic was supplied illegal value: number 1705.4481447162475 exceeded maximum of 1000. See https://git.io/JtMGR for more info.
[05/01/2022, 19:58:03] [Wohnzimmer WavePlus] {"battery":100,"co2":642,"humidity":46,"pressure":952.9,"radonShortTermAvg":96,"rssi":-48,"temp":18.4,"time":1641409069,"voc":556,"relayDeviceType":"hub"}
```

by using [this online converter](http://www.apis.ac.uk/unit-conversion) on the given data with a molecular weight of 78, i would expect a value of about 1.8, not 1705 like in the error message.

![image](https://user-images.githubusercontent.com/11596197/148275793-ceffaef2-68a8-4f17-a88c-d27bce332f98.png)

could it be, that the units "ppm" (as used by airthings) and "ppb" (as used by many formulas) have been mixed?

**Comment by michaelahern** [comment]
The Airthings device [tech specs](https://www.airthings.com/wave-plus) and app show they are measuring VOC as ppb, not ppm. Have you seen any references to ppm in the Airthings ecosystem?

It seems that the [HomeKit Accessory Protocol Spec](https://developer.apple.com/homekit/specification/) has a max value of 1000 for VOC Density, which is what's causing that error message. Seems like that's a low max value if Airthings is measuring ranges >2000 ppb or a reasonable max if they're in fact measuring ppm..

**Comment by benjholl** [comment]
> The Airthings device [tech specs](https://www.airthings.com/wave-plus) and app show they are measuring VOC as ppb, not ppm. Have you seen any references to ppm in the Airthings ecosystem?

i have to apologize: aparently i am the one who mixed up ppm and ppb.
**You are right, VOC is measured in the App/Dashboard and referenced in all of Airthings documents as ppb**.

My bad, sorry. 

Now i am wondering about the homekit max value of 1000, but that ist none of our business i guess...  i think this issue can be closed.
