### ISSUE TITLE
Data View Mini in Homekit

### ISSUE THREAD

**Issue by Bergbock** [michaelahern/homebridge-airthings#9]
Hello, I am using view plus connected to my wlan and pluged with usb power supply. also i do have a wave mini connected to the view plus. my smart home is running on homebridge. the data from the view plus can be seen in apple homekit. how can i also see the data from the wave mini in homekit?
Thanx for support

**Comment by michaelahern** [comment]
When you login to the Airthings Dashboard on their website, do you see data for both your View Plus and Wave Mini? If so, in Homebridge, configure an additional Airthings device (same client id/secret, but with the Wave Mini serial number), and you'll see both in HomeKit.
